name: elyx_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  go_router: ^16.1.0
  google_fonts: ^6.3.2
  retrofit: ^4.0.1
  argon_buttons_flutter_fix: ^1.1.3
  get_it: ^7.6.7
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^5.0.0

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env

  uses-material-design: true
